# Generated by Django 4.0.4 on 2022-05-04 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_walletaddress_owner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WalletAddress',
        ),
    ]
