# Generated by Django 4.0.4 on 2022-05-04 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_walletaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletaddress',
            name='title',
            field=models.CharField(default=None, max_length=10),
        ),
    ]
